services:
  web:
    # the web service definition here
    image: sumitkp497/docker-advance-web:latest
    container_name: advanced-web-container-1
    command: sh -c "yarn install && yarn run dev"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_DB: todos
    networks:
      - docker-advanced-network

  mysql:
    # the database service definition here
    image: mysql:8.0
    container_name: advanced-mysql-container-1
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: todos
    volumes:
      - todo-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - docker-advanced-network

  redis:
    # the cache service definition here
    image: redis:latest
    container_name: advance-redis-container-1
    ports:
      - "6379:6379"
    networks:
      - docker-advanced-network

networks:
  docker-advanced-network:
    driver: bridge
volumes:
  todo-mysql-data:
