name: Docker Image CI

on:
  push:
    branches: [ "main" ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    # checkout the repository
    - name: Checking out repository 
      uses: actions/checkout@v4

    # setting up docker build
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # login to Docker registry (ex. DockerHub)
    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # generate meta tags and labels for Docker Images - web service
    - name: Generate labels and tags
      id: docker-meta-web
      uses: docker/metadata-action@v5
      with:
        images: sumitkp497/docker-advance-web
        tags: |
            latest
  # generate meta tags and labels for Docker Images - cache service
    - name: Generate labels and tags
      id: docker-meta-cache
      uses: docker/metadata-action@v5
      with:
        images: sumitkp497/docker-advance-cache
        tags: |
            latest

  # generate meta tags and labels for Docker Images - DB service
    - name: Generate labels and tags
      id: docker-meta-db
      uses: docker/metadata-action@v5
      with:
        images: sumitkp497/docker-advance-db
        tags: |
            latest

    # build and push docker image - web service
    - name: Build and Push Docker Image for Web Service
      uses: docker/build-push-action@v6
      with:
        push: true
        context: ./webservice/
        tags: ${{ steps.docker-meta-web.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64

# build and push docker image - cache service
    - name: Build and Push Docker Image for Cache Service
      uses: docker/build-push-action@v6
      with:
        push: true
        context: ./cacheservice/
        tags: ${{ steps.docker-meta-cache.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64

        # build and push docker image - db service
    - name: Build and Push Docker Image for DB Service
      uses: docker/build-push-action@v6
      with:
        push: true
        context: ./dbservice/
        tags: ${{ steps.docker-meta-db.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64
        secret-files: |
          "my_secret=./secrets.txt"

    
    

  
