name: Docker Image CI

on:
  push:
    branches: [ "main" ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    # checkout the repository
    - name: Checking out repository 
      uses: actions/checkout@v4

    # setting up docker build
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # login to Docker registry (ex. DockerHub)
    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # build and push docker image
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v6
      with:
        push: true
        platform: linux/amd64










    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
